# Configuration script to Travis-CI
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -e .[test]
  - pip install python-coveralls
script:
  - pytest --cov src/ofxstatement
after_success:
  coveralls
